### ISSUE TITLE
GORM example shall include the otel configuration. For Log, Provider etc.

### ISSUE THREAD

**Issue by systemview2018** [cloudwego/kitex-examples#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by li-jin-gou** [comment]
cc @ViolaPioggia

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/biz-demo/tree/main/easy_note  and whether or not to integrate obs in the gorm example is optional, don't see the need to add it, refer to biz-demo
