### ISSUE TITLE
链路报错

### ISSUE THREAD

**Issue by nihaibao** [cloudwego/kitex-examples#15]
报错信息如下：

2021/10/19 18:44:38.967049 tracer.go:70: [Warn] Panic happened during tracer call. This doesn't affect the rpc call, but may lead to lack of monitor data such as metrics and logs: runtime error: invalid memory address or nil pointer dereference, goroutine 28 [running]:
runtime/debug.Stack(0xc0001a3880, 0x176ca60, 0x1d13d40)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/cloudwego/kitex/internal/stats.(*Controller).tryRecover(0xc000137710, 0x1921198, 0x1d26e48)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/cloudwego/kitex/internal/stats/tracer.go:70 +0x5b
panic(0x176ca60, 0x1d13d40)
	/usr/local/opt/go/libexec/src/runtime/panic.go:965 +0x1b9
github.com/kitex-contrib/tracer-opentracing.(*commonTracer).newCommonSpan(0xc000137740, 0x1924400, 0xc0004147e0, 0x1921238, 0xc0004122a0)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/kitex-contrib/tracer-opentracing/opentracing.go:33 +0x111
github.com/kitex-contrib/tracer-opentracing.(*serverTracer).Finish(0xc000137740, 0x191c9c0, 0xc000418b10)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/kitex-contrib/tracer-opentracing/server.go:54 +0x16e
github.com/cloudwego/kitex/internal/stats.(*Controller).DoFinish(0xc000137710, 0x191c9c0, 0xc000418b10, 0x191e998, 0xc000422960, 0x0, 0x0, 0x1921198, 0x1d26e48)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/cloudwego/kitex/internal/stats/tracer.go:60 +0x130
github.com/cloudwego/kitex/pkg/remote/trans/nphttp2.(*svrTransHandler).finishTracer(0xc000418600, 0x191c9c0, 0xc000418b10, 0x191e998, 0xc000422960, 0x0, 0x0, 0x0, 0x0)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/cloudwego/kitex/pkg/remote/trans/nphttp2/server_handler.go:204 +0x105
github.com/cloudwego/kitex/pkg/remote/trans/nphttp2.(*svrTransHandler).OnRead.func1.1.1(0x9740008, 0xc00058e000, 0xc000418600, 0x191c9c0, 0xc000418b10, 0x191e998, 0xc000422960, 0x0, 0x0)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/cloudwego/kitex/pkg/remote/trans/nphttp2/server_handler.go:118 +0x248
github.com/cloudwego/kitex/pkg/remote/trans/nphttp2.(*svrTransHandler).OnRead.func1.1()
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/cloudwego/kitex/pkg/remote/trans/nphttp2/server_handler.go:149 +0x7bc
github.com/bytedance/gopkg/util/gopool.(*worker).run.func1.1(0xc00013ace0, 0xc00041c940)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/bytedance/gopkg/util/gopool/worker.go:68 +0x62
github.com/bytedance/gopkg/util/gopool.(*worker).run.func1(0xc00013ace0)
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/bytedance/gopkg/util/gopool/worker.go:69 +0xd2
created by github.com/bytedance/gopkg/util/gopool.(*worker).run
	/Users/ellipsis/Apps/hhz_go/passport-kitex/vendor/github.com/bytedance/gopkg/util/gopool/worker.go:41 +0x3f

代码如下：
![image](https://user-images.githubusercontent.com/7386005/137894872-e8c21bfd-a868-494a-95dd-c8ffe39f43a8.png)
![image](https://user-images.githubusercontent.com/7386005/137894965-462a7ca0-4dad-4496-afca-d766a326ed68.png)

**Comment by lifang218c** [comment]
Go调用，在client端，也使用initjeager不报错。可以正常执行和正常数据上报
php 调用的时候，会报错。 因为追踪代码发现是这个错误：github.com/kitex-contrib/tracer-opentracing/opentracing.go。  33行。调试发现，这行：

`readSpan := c.newEventSpan("read", st, stats.ReadStart, stats.ReadFinish, span.Context())
readSpan.SetTag("recv_size", st.RecvSize())    `

这个readSpan是空的

**Comment by lifang218c** [comment]
强！  挺速度的呢？  正在发愁怎么解决，本来想通过中间件来弄这个事，没想到这么快就修复了。 @BytedanceRPC   这个event追踪代码发现，需要调用那个提供的record 方法来生成对应的evenmap才能再次使用。。  然后这个eventmap 有12种类型。如果是php调用 只会 生成 5，1，2，6 四种事件。但是go调用的话，会依次生成5，7，8，1，2，11，12，6。

等下看看你修复的代码，感谢🙏
