### ISSUE TITLE
能不能提供一个完整的Example

### ISSUE THREAD

**Issue by YLzpppp** [cloudwego/kitex-examples#18]
能不能提供一个稍微完整点的示例项目呀、也更方便没接触过的人快速熟悉kitex呀。比如一个包含 鉴权、用户、文章三个模块的小示例。

**Comment by simon0-o** [comment]
你说的这些已经涉及到了数据库等一些其他基础设施，超出了一个 RPC 框架的 demo 范围。

**Comment by YangruiEmma** [comment]
> 能不能提供一个稍微完整点的示例项目呀、也更方便没接触过的人快速熟悉kitex呀。比如一个包含 鉴权、用户、文章三个模块的小示例。

我们后面会出一个Kitex使用案例，业务更丰富的使用方式也期待大家来补充 https://github.com/cloudwego/kitex/issues/156
