### ISSUE TITLE
Can't find this dependency

### ISSUE THREAD

**Issue by lancelot6806** [cloudwego/kitex-examples#2]
https://github.com/cloudwego/kitex-examples/blob/main/tracer/server/opentracing/main.go

internal_opentracing "github.com/kitex-contrib/opentracing"

https://github.com/kitex-contrib  This organization has no public repositories.

**Comment by simon0-o** [comment]
opensource application for `github.com/kitex-contrib/opentracing` is still in progress, it might take one or two weeks

**Comment by ssolid2014** [comment]
> opensource application for `github.com/kitex-contrib/opentracing` is still in progress, it might take one or two weeks

Is there an ETA for this?

**Comment by simon0-o** [comment]
We have to rename the repo to `github.com/kitex-contrib/tracer-opentracing`, and it's available now.
