### ISSUE TITLE
如何通过kitex命令生成类似bizdemo/easy_note中的目录结构

### ISSUE THREAD

**Issue by h1deOnBush** [cloudwego/kitex-examples#30]
kitex如何指定生成service的路径，从而类似easy_note中的目录结构一样。使用常规的kitex -service demo demo.thrift只能生成这样的目录结构
.
├── build.sh                     // 服务的构建脚本，会创建一个名为 output 的目录并生成启动服务所需的文件到里面
├── handler.go                   // 用户在该文件里实现 IDL service 定义的方法
├── kitex_gen                    // IDL 内容相关的生成代码
│   ├── base                     // base.thrift 的生成代码
│   │   ├── base.go              // thriftgo 的产物，包含 base.thrift 定义的内容的 go 代码
│   │   └── k-base.go            // kitex 在 thriftgo 的产物之外生成的代码
│   └── demo                     // demo.thrift 的生成代码
│       ├── demo.go              // thriftgo 的产物，包含 demo.thrift 定义的内容的 go 代码
│       ├── k-demo.go            // kitex 在 thriftgo 的产物之外生成的代码
│       └── demoservice          // kitex 为 demo.thrift 里定义的 demo service 生成的代码
│           ├── demoservice.go   // 提供了 client.go 和 server.go 共用的一些定义
│           ├── client.go        // 提供了 NewClient API
│           └── server.go        // 提供了 NewServer API
├── main.go                      // 程序入口
└── script                       // 构建脚本
    └── bootstrap.sh             // 服务的启动脚本，会被 build.sh 拷贝至 output 下

而easy_note中的代码结构中通过kitex生成的script/*、main.go和handler.go与kitex_gen不在同一个目录下，这是怎么做到的，是自己复制的吗，那这样每次都需要自己手动修改handler.go中的包名很麻烦啊

**Comment by li-jin-gou** [comment]
参考 https://www.cloudwego.io/zh/docs/kitex/tutorials/code-gen/code_generation/#-use-path
