### ISSUE TITLE
请问如果三个模块分别用Docker打包，kitex容器间的服务注册发现要如何实现呢？

### ISSUE THREAD

**Issue by gityh2021** [cloudwego/kitex-examples#34]
本地环境下的注册发现是可以实现的，但是打包成容器运行之后就不行了。

**Comment by GuangmingLuo** [comment]
用的哪个例子？本地使用什么方案做注册发现？

**Comment by gityh2021** [comment]
easy note那个例子，本地使用etcd作为注册中心去做服务发现

**Comment by GuangmingLuo** [comment]
@justlorain hi, 能否在 [easy_note](https://github.com/cloudwego/biz-demo/tree/main/easy_note) 这个项目加一个 Dockerfile 以及 Docker run 的启动方式？ETCDAddress 常量可以支持在 Dockerfile 和运行时配置

**Comment by gityh2021** [comment]
May I try it?

**Comment by gityh2021** [comment]
> > @justlorain hi, 能否在 [easy_note](https://github.com/cloudwego/biz-demo/tree/main/easy_note) 这个项目加一个 Dockerfile 以及 Docker run 的启动方式？ETCDAddress 常量可以支持在 Dockerfile 和运行时配置
> 
> OK

May I try this?

**Comment by justlorain** [comment]
> > > @justlorain hi, 能否在 [easy_note](https://github.com/cloudwego/biz-demo/tree/main/easy_note) 这个项目加一个 Dockerfile 以及 Docker run 的启动方式？ETCDAddress 常量可以支持在 Dockerfile 和运行时配置
> > 
> > 
> > OK
> 
> May I try this?

Sure, looking forward to your PR ❤️
