### ISSUE TITLE
在本地环境Mac m1下启动Etcd报端口占用，请问怎么解决

### ISSUE THREAD

**Issue by MingWangSong** [cloudwego/kitex-examples#40]
{"level":"fatal","ts":"2022-07-27T08:01:16.260Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 127.0.0.1:2380: bind: address already in use","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/go/gos/go1.16.15/src/runtime/proc.go:225"}

**Comment by ppzqh** [comment]
没太理解这个问题，使用了 etcd 作为注册中心吗？这个报错如 log 中所示，监听的端口被占用了。

**Comment by MingWangSong** [comment]
对，我是使用了 etcd 作为注册中心，在docker中启动就报错，我后面试了几次后，突然启动起来了，没看懂
