### ISSUE TITLE
otel-collector配置victoriametrics域名不生效

### ISSUE THREAD

**Issue by huanghanx1n** [cloudwego/kitex-examples#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Kitex version:**

Please provide the version of Kitex you are using.

**Environment:**

The output of `go env`.

**Additional context**

使用kitex-examples/opentelemetry，otel-collector配置victoriametrics域名不生效，导致metrics没有指标数据

**Comment by li-jin-gou** [comment]
As mentioned in the communication, is it possible to provide `playgound` and more detail info? we are running normally.

**Comment by rogerogers** [comment]
and the latest otel-collector logs please.
