### ISSUE TITLE
希望提供 Trans 使用 gonet 的示例。

### ISSUE THREAD

**Issue by rectcircle** [cloudwego/kitex-examples#50]
1. 文档 https://www.cloudwego.io/zh/docs/kitex/tutorials/framework-exten/transport/ 提供了定制传输层的说明，比较抽象，作为框架使用者不知道怎么用。
2. changelog https://www.cloudwego.io/zh/blog/2022/08/26/kitex-v0.4.0-%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83/  提到 v0.4.0 支持了 gonet 作为传输层，只说在 window 场景作为默认的传输层。但没有说明如何强制指定。

诉求：

1. https://www.cloudwego.io/zh/docs/kitex/tutorials/framework-exten/transport/  文档添加如何使用 [gonet](https://github.com/cloudwego/kitex/blob/develop/pkg/remote/trans/gonet/) 配置的示例。
2. example 代码库添加关于传输层配置的示例，比如，添加一个可运行的 demo， 这个 demo 配置使用 gonet 作为传输层。

**Comment by GuangmingLuo** [comment]
@HeyJavaBean 是否考虑完善下官网文档呢？

**Comment by HeyJavaBean** [comment]
写法如下
```
var opts []server.Option
opts = append(opts, server.WithTransServerFactory(gonet.NewTransServerFactory()))
opts = append(opts, server.WithTransHandlerFactory(gonet.NewSvrTransHandlerFactory()))
svr := xxxservice.NewServer(handler, opts...)
```
