### ISSUE TITLE
请问是否有搭建 easy_note 项目的流程

### ISSUE THREAD

**Issue by zztaki** [cloudwego/kitex-examples#58]
**Is your feature request related to a problem? Please describe.**

刚刚了解到了 gorm、kitex、hertz 框架的强大之处，但它们的教程往往是孤立的，只涉及各自的单独使用。我觉得 easy_note 这个项目很适合将这三个框架串起来，但只有 quick start，而没有使用这三个框架逐渐构建出这个项目的教程。

**Describe the solution you'd like**

希望有这样一个教程：使用 gorm、kitex、hertz 一步一步构建出这个笔记项目，增强自身的一些自信心。

**Comment by justlorain** [comment]
可以参考一下 [cloudwego/biz-demo](https://github.com/cloudwego/biz-demo) 下的 `easy_note`，项目框架基本是按照 `kitex` 和 `hz` 工具生成的脚手架来的，之后也会出专门的文字解读，可以关注一下 CloudWeGo 公众号

**Comment by li-jin-gou** [comment]
类似的详细教程正在写，敬请期待.😁

**Comment by GuangmingLuo** [comment]
代码解读可以参考这个直播回放：https://meetings.feishu.cn/s/1iraydxgioe81
PPT: [EasyNote——CloudWeGo 生态入门](https://github.com/cloudwego/community/blob/main/CSG/04/EasyNote%E2%80%94%E2%80%94CloudWeGo%20%E7%94%9F%E6%80%81%E5%85%A5%E9%97%A8.pdf)

**Comment by zztaki** [comment]
> 代码解读可以参考这个直播回放：https://meetings.feishu.cn/s/1iraydxgioe81 PPT: [EasyNote——CloudWeGo 生态入门](https://github.com/cloudwego/community/blob/main/CSG/04/EasyNote%E2%80%94%E2%80%94CloudWeGo%20%E7%94%9F%E6%80%81%E5%85%A5%E9%97%A8.pdf)

感谢回复！
