### ISSUE TITLE
求助：easy_note项目在windows下build note报错

### ISSUE THREAD

**Issue by MingWangSong** [cloudwego/kitex-examples#59]
`
# github.com/cloudwego/netpoll                                                                       
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\connection.go:59:18: undefined: OnRequest
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\connection_impl.go:30:2: undefined: netFD
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\connection_impl.go:41:19: undefined: barrier
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\connection_impl.go:42:19: undefined: barrier
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\connection_impl.go:48:20: cannot use &connection{} (value of type *connection) as type Connec
tion in variable declaration:
        *connection does not implement Connection (missing LocalAddr method)
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\connection_impl.go:299:32: undefined: Conn
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\netpoll_options.go:80:14: undefined: OnPrepare
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\netpoll_options.go:81:14: undefined: OnConnect
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\netpoll_options.go:82:14: undefined: OnRequest
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\netpoll_server.go:37:14: undefined: Listener
..\..\..\goPath\pkg\mod\github.com\cloudwego\netpoll@v0.2.0\connection_impl.go:299:32: too many errors
# github.com/choleraehyq/pid
..\..\..\goPath\pkg\mod\github.com\choleraehyq\pid@v0.0.13\pid_go1.5_amd64.s:28: expected pseudo-register; found R13
..\..\..\goPath\pkg\mod\github.com\choleraehyq\pid@v0.0.13\pid_go1.5_amd64.s:29: expected pseudo-register; found R14
asm: assembly of ..\..\..\goPath\pkg\mod\github.com\choleraehyq\pid@v0.0.13\pid_go1.5_amd64.s failed

`

**Comment by justlorain** [comment]
kitex, netpoll 不支持 windows，建议使用 WSL

**Comment by MingWangSong** [comment]
催更支持一波windows

**Comment by justlorain** [comment]
> 催更支持一波windows

参考 https://github.com/cloudwego/kitex/issues/766

**Comment by li-jin-gou** [comment]
> kitex, netpoll 不支持 windows，建议使用 WSL

需要更新一波版本了，最新的 kitex 正常是支持在 winfows 上编译&运行的。
