### ISSUE TITLE
[BUG] Error compiling Dockerfile due to low Go version

### ISSUE THREAD

**Issue by shiw-yang** [cloudwego/kitex-examples#70]
**Describe the bug**

根据readme描述，使用dockerfile对项目进行编译的时候，执行到编译项目时报go版本低于1.17无法完成编译
**To Reproduce**

1. run `docker build -t kitex-examples .`
2. see：
```log
#12 86.98 /go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall.go:83:16: undefined: unsafe.Slice
#12 86.98 /go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_linux.go:2271:9: undefined: unsafe.Slice
#12 86.98 /go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
#12 86.98 /go/pkg/mod/golang.org/x/sys@v0.5.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
#12 86.98 note: module requires Go 1.17
------
executor failed running [/bin/sh -c go build -o hello-client ./hello/client]: exit code: 2
```

**Expected behavior**
将dockerfile内的镜像版本选为`golang:1.18.10-alpine`可以编译通过

**Screenshots**

**Kitex version:**

```bash
$ kitex --version
v0.5.2
```

**Comment by li-jin-gou** [comment]
这不是一个 bug && golang 本身的版本不兼容，如题 https://stackoverflow.com/questions/74049351/gcloud-functions-deploy-go-runtime-error-undefined-unsafe-slice-error-id-2f5
