### ISSUE TITLE
请问windows环境下如何把easy_note项目网络库替换成gonet

### ISSUE THREAD

**Issue by Zjuwjx** [cloudwego/kitex-examples#71]
netpoll不支持windows，请问如何进行替换。另外请问是否有支持windows的计划？

**Comment by li-jin-gou** [comment]
@Zjuwjx  升级 kitex 的版本到最新即可。

**Comment by GuangmingLuo** [comment]
现在 example 代码库的Kitex版本已经支持在 Windows 环境下运行了，基于性能考虑，不用再替换成 Go net 了。

**Comment by Zjuwjx** [comment]
panic: interface conversion: *gonet.bufioConn is not netpoll.Connection: missing method AddCloseCallback 
请问测试注册接口的时候报这个错误是什么原因。

**Comment by li-jin-gou** [comment]
去 kitex 仓库下翻翻 issue 吧，怀疑是已知问题，可能更新一下 kitex 版本就好了，如果都不能解决就提个 kitex 的i ssue 吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月20日(周六) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [cloudwego/kitex-examples] 请问windows环境下如何把easy_note项目网络库替换成gonet (Issue #71)




 
panic: interface conversion: *gonet.bufioConn is not netpoll.Connection: missing method AddCloseCallback
 请问测试注册接口的时候报这个错误是什么原因。
