### ISSUE TITLE
Proposal: Build an API Gateway Based on CloudWeGo Projects

### ISSUE THREAD

**Issue by felix021** [cloudwego/kitex-examples#75]
# Goal

The primary goal of this proposal is to implement a demo API Gateway on [Hertz](https://github.com/cloudwego/hertz) which accepts HTTP requests encoded in JSON format and uses the Generic-Call feature of [Kitex](https://github.com/cloudwego/kitex) to translate these requests into Thrift binary format requests. The API Gateway will then forward the request to one of the backend RPC servers discovered from the registry center.

# Requirements and Deliverables

1. Implement an API Gateway that accepts HTTP requests with JSON-encoded bodies.
2. Use the Generic-Call feature in Kitex to translate JSON requests into Thrift binary format.
3. Integrate a load balancing mechanism to distribute requests among backend RPC servers.
4. Integrate a service registry and discovery mechanism for the API Gateway and RPC servers.
5. Develop backend RPC servers using Kitex for testing the API Gateway.
6. Document the project, including design decisions, implementation details, and usage instructions.

You're encouraged to post your implementation here for others' reference.

Template:

> Project Name: 
> Authors: [feel free to mention your github id, email, school/company, and/or any other information you'd like to provide]
> Github: [url]
> Documentation: [url]
> Description: [brief introduction on your project]

**Comment by yiwen101** [comment]
Project Name: API Gateway
Author: GitHub id: yiwen101, email: e0968880@u.nus.edu
Github: https://github.com/yiwen101/CardWizards
Description: A working API Gateway that support runtime behavior control and come with a functional control web GUI. Applied listener pattern to maintain the idl to client map in run time. Still a work in progress, plan to add support for plugins, error handling etc

**Comment by tanyyyming** [comment]
- Project Name: orbital_HeBao
- Author: [Wang Hejin](https://github.com/wanghejin), [Tan Yiming](https://github.com/tanyyyming). Our emails are hj827458@gmail.com and tanyiming.nus@gmail.com.
- Repo: https://github.com/wanghejin/orbital_HeBao
- Documentation: https://lively-cereal-3a1.notion.site/API-Gateway-based-on-CloudWeGo-Projects-e59b321209f043a0a625a8c98364c838?pvs=4
- Description: 
The scope of our project is to develop a fully functioning API gateway in Golang under the two frameworks: CloudWeGo's Kitex (an RPC framework) and Hertz (an HTTP framework). In this project, we focused on implementing four core features for our API gateway: 

  1. service registration and discovery; 
  2. communication protocol translation from HTTP to Thrift binary protocol;
  3. load balancing;
  4. dynamic updating of the mapping between interface definition language (IDL) files and backend microservices.

  After completing the demo product, we also conducted unit testing, integration testing, and performance testing on it.

**Comment by simbayippy** [comment]
Project Name: Svb_2.0

Author [Yip Sin Hang](https://github.com/simbayippy), [Niu wen jia](https://github.com/wj331). Our emails are [simbayippy@gmail.com](simbayippy@gmail.com) and [wenjia9niu@gmail.com](wenjia9niu@gmail.com).

Repo: [https://github.com/simbayippy/OrbitalxTikTok](https://github.com/simbayippy/OrbitalxTikTok)

Documentation: [here](https://orbital-tiktok.gitbook.io/orbital-tiktok/main-assignment/team-svb2.0-orbital-tiktok)

Description: A High performance API Gateway that is able to dynamically update any service updates in IDL file during run time, supporting the 4 different types of generic clients of Kitex. Additional attempts made for the protojson_codec was made - close but still a work in progress

The full scope of our project can be found in our documentation process.

**Comment by jieqiboh** [comment]
### Project Name: _Godzilla Gateway_ (Inspired from the [Kong API Gateway](https://konghq.com/products/kong-gateway))

Authors: [Boh Jie Qi](https://github.com/jieqiboh), [Winson Zheng](https://github.com/winson8222), our emails are e0937187@u.nus.edu and e0559763@u.nus.edu respectively.

Repo: https://github.com/jieqiboh/Godzilla-Gateway

Documentation: This [page](https://docs.google.com/document/d/1A5tsdLtYHZtmRj8d687VEJ4mpSL_pWx63wjGD-aYFnQ/edit#heading=h.z6ne0og04bp5) provides links to our entire submission, including the system design document, relevant setup videos, and github repositories

Description:
A tested, highly performant, full-fledged API Gateway that implements all the basic requirements listed above:
- Accepts HTTP requests with json payloads and routes them to the respective services
- Employs the Kitex Generic Call mechanism to make json generic calls to microservices
- Utilises an etcd cluster as part of microservice registration and service discovery, as well as load-balancing mechanisms

Our API Gateway also provides the following features:
- Fully functioning IDL management system with an easy-to-use UI, enabling users to register, update and delete microservices for their API Gateway
- Code Generator that is able to generate gateway code based on microservices registered on the fly
- Elaborate gateway architecture comprising multiple gateway instances and an NGINX reverse proxy that allows for smooth updating of the gateway while it is running.

We also made our own custom benchmarking tool using Apache Bench that is able to measure key metrics like TP99 and QPS for our gateway, and made a [cool logo](https://github.com/cloudwego/kitex-examples/assets/93033071/be514c8e-2941-4fc3-9656-c676dbf1295b) :)

**Comment by 1rbg** [comment]
Project Name: API Gateway

Authors: [Gabriel Chua](https://github.com/1rbg), [Loh Jian Rong](https://github.com/jianrong7). Our emails are [](gabrielchua29@gmail.com) and [](lohjianrong7@gmail.com) respectively.

Repo: [](https://github.com/jianrong7/orbital-23)

Documentation: This [page](https://docs.google.com/document/d/1EGI23ZpKZHFpL88zSKpXoLZyC-oAF9YmwzIHkDahWR4/edit?usp=sharing) provides links to our entire submission, including the system design document, cloud deployment documentation, as well as testing.

Description:

A working API Gateway that is able to support server-side updates to the IDL, and service registration using Consul. It supports the JSON Generic Call function of the Kitex framework.

**Comment by RashawnXue** [comment]
Project Name: **CloudWeGo-API-Gateway**

Authors:
- [RashawnXue](https://github.com/RashawnXue)([ruichenxue@smail.nju.edu.cn](mailto:ruichenxue@smail.nju.edu.cn)), 
- [Jxd12](https://github.com/Jxd12)([2215882421@qq.com](mailto:2215882421@qq.com))
- [liukedian](https://github.com/liukedian)([1260746107@qq.com](mailto:1260746107@qq.com))

Repo: https://github.com/RashawnXue/CloudWeGo-API-Gateway

Documentation: You can find the documents of the project in [README.md](https://github.com/RashawnXue/CloudWeGo-API-Gateway/blob/main/README.md) and this [page](https://qiyaq6lc2gg.feishu.cn/wiki/R427wrwbziumfWkK4wwcdaugnlh)

Description: 
- The project implemented an API Gateway with two CloudWeGo' s frameworks: Hertz and Kitex. 
- The client can send HTTP requests to the Gateway, then it will generic and forward the requests to the corresponding RPC servers.
- It supports IDL management, which allows to hot update IDL.

**Comment by lar0129** [comment]
Project Name: Hertz API-gateway

Authors:

* [lar0129](https://github.com/lar0129)(email: 211250127@smail.nju.edu.cn),
* [wangchunchia](https://github.com/wangchunchia)(email: 211250206@smail.nju.edu.cn),
* [tcrxcenzdyrclb](https://github.com/tcrxcenzdyrclb)(email: 211250023@smail.nju.edu.cn)


Repo: https://github.com/lar0129/hertz-APIgateway

Documentation:  
* Chinese version: [README](https://github.com/lar0129/hertz-APIgateway)
* English version: To be continued

Description:

* In this project, the API gateway serves as the entry point for the system, receives all incoming HTTP requests, parses the URLs in the requests, forwards them to the relevant back-end RPC servers in JSON format, retrieves the responses, and returns them to the clients.
* It supports IDL management, load balancing mechanism, service registry and discovery mechanism

**Comment by sherry-500** [comment]
Project Name: Cloudwego Apigateway

Authors:


- [sherry-500](https://github.com/sherry-500)(email: [apriln070@gmail.com](mailto:apriln070@gmail.com)),

- [Supernova114514](https://github.com/Supernova114514)(email: [1436884633@qq.com](mailto:1436884633@qq.com))

Repo: https://github.com/sherry-500/apigateway

Documentation:

- Chinese version: [README](https://github.com/sherry-500/apigateway)

- English version: To be continued

Description:

The project implemented an API Gateway with two CloudWeGo' s frameworks: Hertz and Kitex. In this project, the API gateway accepts HTTP requests with json payloads and routes them to the respective services, retrieves the responses, and returns them to the clients. It also supports IDL management, which allows to hot update IDL.

**Comment by JiaXinEu** [comment]
Project Name: API_Gateway
Authors: 

- [Yashma Sonara](https://github.com/yashma-sonara) (Email: yashma.sonara04@gmail.com)

- [Jia Xin Eu](https://github.com/JiaXinEu) (Email: tis8cjiaxineu@gmail.com) 

Github: https://github.com/yashma-sonara/API_Gateway

Documentation: [System Design Document](https://docs.google.com/document/d/1bZaO5qUFYXNJyYOHK0VpxGImuBUHVA95W88Dq98cDic/edit?usp=drive_link)

Demo:  [Demo Video ](https://drive.google.com/file/d/1BrSShac52ABtne1ZVjP-F44xYzO0D_o1/view?usp=drive_link)

Description:  This project is an API Gateway implementation that serves as a centralized entry point for accessing and managing multiple backend services. Our project includes: 

- Built using Golang upon the Hertz and Kitex frameworks.

- Enables service registry Nacos and dynamic IDL updates.

- Translates HTTP requests encoded in JSON format into Thrift binary format using Kitex Generic Call feature.

- Load balancing through weighted round robin.

- Unit, integration testing and benchmarking.

**Comment by iksars** [comment]
Project Name: cloudwego-api-gateway

Authors: 

- [iksar](https://github.com/iksars)
- [Yeahhooooo](https://github.com/Yeahhooooo)
- [windloong](https://github.com/windloong)

Github: [https://github.com/iksars/cloudwego-api-gateway](https://github.com/iksars/cloudwego-api-gateway)

Documentation: [docs ](https://github.com/iksars/cloudwego-api-gateway/tree/main/docs)


Description: Our project implements the following functions
1.basic api gateway functions

2.lruCache optimization for generic call client

3.idl management platform(frontend & backend) which support to curd IDL file and manage service interface

4.api gateway support IDL dynamically update

**Comment by SYuan03** [comment]
**Project Name:** 

[apigateway](https://github.com/SYuan03/apigateway)

**Authors:**

[TwinDagger](https://github.com/SYuan03)
[Jiao-Yiyang](https://github.com/Jiao-Yiyang)
[ARK_Fung](https://github.com/ARKFzy)

**Github:** 

https://github.com/iksars/cloudwego-api-gateway

**Documentation:** 

[apidoc](https://github.com/SYuan03/apigateway/blob/main/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3.md)
[idl-management-platform doc](https://github.com/SYuan03/apigateway/blob/main/IDL%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3.md)
[deploy doc1](https://github.com/SYuan03/apigateway/blob/main/DeployDoc1.md)
[deploy doc2](https://github.com/SYuan03/apigateway/blob/main/DeployDoc2.md)

**Description:** 

Here are the features and technologies used in our project:

1. basic api gateway functions : we use studentservice as example

2. client: we use [Hertz](https://www.cloudwego.io/zh/docs/hertz/) to generate the sample code of client

3. idl management platform

4. Service-side: generated by idl using [Kitex](https://github.com/cloudwego/kitex)

5. etcd
